version: '3.8'

services:
  relative_db:
    image: mysql:latest
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d    
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3307:3306"
    restart: always